version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: doctor-base:latest


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - doctor-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  crawl_worker:
    build:
      context: .
      dockerfile: src/crawl_worker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - REDIS_URI=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - DB_SYNC_INTERVAL_SEC=10
    depends_on:
      redis:
        condition: service_healthy
      base:
        condition: service_completed_successfully

    networks:
      - doctor-net

  web_service:
    build:
      context: .
      dockerfile: src/web_service/Dockerfile
    ports:
      - "9111:9111"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - REDIS_URI=redis://redis:6379
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    depends_on:
      redis:
        condition: service_healthy
      base:
        condition: service_completed_successfully

    networks:
      - doctor-net

networks:
  doctor-net:
    driver: bridge
